### ISSUE TITLE
Not recording the illustrator on screen. It only keeps showing the menu bar and desktop screen.

### ISSUE THREAD

**Issue by luico001** [ansonsiva/screenTimelapseZ#7]
I only have 1 desktop running when I record, I used to use this tool to record timelapse of my illustration on Adobe illustrator to showcase my progress. But it stopped doing that for me now. Please help! Mac version is 12.4 on Monterey.

**Comment by luico001** [comment]
https://user-images.githubusercontent.com/125120815/218249021-13b3e3b9-6abc-4034-a094-f130c960dd32.mp4

**Comment by ansonsiva** [comment]
Thank you for reaching out to us regarding the issues you have been experiencing with our screen recording software. I am sorry to hear that you have been encountering difficulties.

May I kindly ask if you have made any recent changes to your macOS privacy and security settings? Also, have you recently updated your system? Another possibility could be that your trial version has expired.

In order to better assist you, could you please try recording and let me know if you are able to capture the content?

Additionally, could you please provide your email address so that I can follow up with you and assist you further in resolving this issue?

Thank you for your time and I look forward to hearing back from you.

Best regards

**Comment by ansonsiva** [comment]
It is also possible that you have not granted the app permission in your privacy and security settings, which is why you are unable to capture the content on the screen. You can open the permission for Screen TimelapseZ/lite in the screen recording menu under the privacy and security menu in the macOS system settings. This issue seems to be similar to the one discussed at https://github.com/ansonsiva/screenTimelapseZ/issues/3.

**Comment by luico001** [comment]
@ansonsiva thank you! It was the privacy and security. It is working again now!
